# Unique name for this workflow
name: Salesforce DX PR (packaging)

# Definition when the workflow should run
on:
    schedule:
    - cron: "0 0 * * *"


# Jobs to be executed
jobs:
    formatting-and-linting:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                ref: develop

            # Install Salesforce CLI
            - name: Install Salesforce CLI
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
                  mkdir sfdx-cli
                  tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
                  ./sfdx-cli/install
            
             # Install sfpowerkit
            - name: Install sfpowerkit
              run: |
                  echo'y' | sfdx plugins:install sfpowerkit

             # Install sfpowerscripts
            - name: Install sfpowerscripts
              run: |
                  echo 'y' | sfdx plugins:install @dxatscale/sfpowerscripts@alpha

            # Store secret for dev hub
            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
              shell: bash
              run: 'echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'


            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'


            # Validate source and trigger test
            - name: 'Push source to scratch org'
              run: 'sfdx sfpowerscipts:orchestrate:prepare -t CI1 -v devhub --installall --installassourcepackages'

